# position-only-ik and orientation-only-ik don't work unless position_only_ik
# is set to true for the KDL and trac_ik plugins

# testing_environment:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
#   kinematics_solver_attempts: 3
#   position_only_ik: true

# testing_environment:
#   kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
#   kinematics_solver_timeout: 0.005
#   solve_type: Speed
#   position_only_ik: true

# Position-only-ik and orientation-only-ik work even if position_only_ik is not set below

# testing_environment:
#   kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
#   kinematics_solver_attempts: 3
  # position_only_ik: true

wx200_arm_A/arm_controller:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_timeout: 0.005
  solve_type: Speed
  position_only_ik: true

wx200_arm_B/arm_controller:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_timeout: 0.005
  solve_type: Speed
  position_only_ik: true

# wx200_arm_A/gripper_controller:
#   kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
#   kinematics_solver_timeout: 0.005
#   solve_type: Speed
#   position_only_ik: true
#
# wx200_arm_B/gripper_controller:
#   kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
#   kinematics_solver_timeout: 0.005
#   solve_type: Speed
#   position_only_ik: true
